export const cities = [
  "Dhaka",
  "Rajshahi",
  "Sylhet",
  "Chattogram",
];

export const cityThanas: Record<string, string[]> = {
  Dhaka: [
    "Uttara",
    "Airport",
    "Turag",
    "Dakshinkhan",
    "Badda",
    "Gulshan",
    "Banani",
    "Cantonment",
    "Mirpur",
    "Pallabi",
    "Kafrul",
    "Shah Ali",
    "Darus Salam",
    "Adabar",
    "Mohammadpur",
    "Tejgaon",
    "Tejgaon Industrial Area",
  ],
  Rajshahi: [
    "Boalia",
    "Shah Mokhdum",
    "Chatmohar",
    "Paba",
    "Motihar",
    "Godagari",
  ],
  Sylhet: [
    "Sylhet Sadar",
    "Zindabazar",
    "Ambarkhana",
    "Subidbazar",
    "Shibganj",
  ],
  Chattogram: [
    "Chattogram Sadar",
    "Pahartali",
    "Panchlaish",
    "Kotwali",
    "Double Mooring",
    "Halishahar",
    "Chandgaon",
    "Bayezid",
  ],
};
